name: SunwayBlog Deployment
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy to my VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            echo "Before PATH modification:"
            echo $PATH
            which yarn || echo "yarn not found"
            export PATH="/root/.nvm/versions/node/v20.18.0/bin:$PATH"
            echo "After PATH modification:"
            echo $PATH
            which yarn || echo "yarn not found"
            cd /app/sunwayBlog
            git pull
            yarn install
            yarn build
            
